### ISSUE TITLE
AttributeError: 'PluginLoader' object has no attribute 'get_with_context'

### ISSUE THREAD

**Issue by arrfab** [mitogen-hq/mitogen#770]
When using mitogen from master branch, ansible now tracebacks with the following error :

```
ansible -m ping all -vvv
ansible 2.9.16
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

ERROR! Unexpected Exception, this is probably a bug: 'PluginLoader' object has no attribute 'get_with_context'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible", line 123, in <module>
    exit_code = cli.run()
  File "/usr/lib/python3.6/site-packages/ansible/cli/adhoc.py", line 166, in run
    result = self._tqm.run(play)
  File "/usr/lib/python3.6/site-packages/ansible/executor/task_queue_manager.py", line 261, in run
    strategy = strategy_loader.get(new_play.strategy, self)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/loader.py", line 552, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/loader.py", line 525, in _load_module_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/tobisna-dev/mitogen-master/ansible_mitogen/plugins/strategy/mitogen_linear.py", line 55, in <module>
    import ansible_mitogen.loaders
  File "/var/lib/tobisna-dev/mitogen-master/ansible_mitogen/loaders.py", line 62, in <module>
    connection_loader__get = connection_loader.get_with_context
AttributeError: 'PluginLoader' object has no attribute 'get_with_context'

```
It happens on CentOS 8, with ansible-2.9.16-1.el8.noarch , using default python 3.6.8 and mitogen from current master branch.
But it was working some days ago, so I just tried to revert to specific tag https://github.com/dw/mitogen/releases/tag/v0.2.10-rc.0 and then it worked again.

**Comment by s1113950** [comment]
Current `master` right now works with Ansible 2.10+, but it should have told you that rather than erroring 🤔 so this is most definitely a bug. If you need Ansible < 2.10 support, please try this new tag:
https://github.com/dw/mitogen/releases/tag/v0.2.10-rc.0
and if you'd like Ansible 2.10+ support please try this one: https://github.com/dw/mitogen/releases/tag/v0.3.0-rc.0

**Comment by arrfab** [comment]
yeah, as said that's what I did : reverting to specific tag .. ideally there would be some "releases" reflecting that and just curious : why isn't that backward compatible ? Ansible 2.9 branch is still itself being supported, so was surprised to see that mitogen wouldn't work with it (outside of specific tag that is)

**Comment by s1113950** [comment]
Ooh you're right, my bad I missed that, thanks for clarifying. See this large thread if you're curious, with a TL;DR here: https://github.com/dw/mitogen/pull/715#issuecomment-750697248 . Mitogen decided to break backwards compatibility because Ansible's API changed too much. For this reason, 0.2.10 is going to support up to Ansible 2.9 and 0.3.0 will support Ansible 2.10+.
