### ISSUE TITLE
Ansible 14: dnf module list returns No start of json char found

### ISSUE THREAD

**Issue by dygland** [mitogen-hq/mitogen#1558]
### Description

This seems to be very similar to https://github.com/mitogen-hq/mitogen/issues/1529 but only affects the list command, there seems to be some handling of the list-command in https://github.com/mitogen-hq/mitogen/blob/master/ansible_mitogen/_modifiers.py#L34 but i am not sure how the modifiers work.

When running a task such as:
```yaml
- name: find all available packages
   ansible.builtin.dnf
     list: "httpd-*"
    register: available_packages
```

Mitogen failes with the following error/stack trace:
```
TASK [httpd : Find all available packages] *****************************
[ERROR]: Task failed: Action failed: Module result deserialization failed: No start of json char found                                                                                                                                                           
                                                                                                                                                                                                                                                                 
Task failed: Action failed.                                                                                                                                                                                                                                      
Origin: /home/dygland/git/ansible/roles/httpd/tasks/main.yml:26:3                                    

24   when: ansible_facts.packages['httpd'] is defined
25
26 - name: Find all available packages
     ^ column 3

<<< caused by >>>

Module result deserialization failed: No start of json char found See stdout/stderr for the returned output.

fatal: [hostname.domain.tld]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

Module result deserialization failed: No start of json char found

                                                                                                                                                                                                                                                                                                                                
MODULE_STDERR:

Traceback (most recent call last):
  File "master:/home/dygland/git/ansible/.venv/ansible14/lib64/python3.12/site-packages/ansible_mitogen/runner.py", line 1062, in _run
    self._run_code(code, mod)
  File "master:/home/dygland/git/ansible/.venv/ansible14/lib64/python3.12/site-packages/ansible_mitogen/runner.py", line 1017, in _run_code
    exec(code, vars(mod))
  File "master:/home/dygland/git/ansible/.venv/ansible14/lib64/python3.12/site-packages/ansible/modules/dnf.py", line 675, in <module>
  File "master:/home/dygland/git/ansible/.venv/ansible14/lib64/python3.12/site-packages/ansible/modules/dnf.py", line 671, in main
  File "master:/home/dygland/git/ansible/.venv/ansible14/lib64/python3.12/site-packages/ansible/modules/dnf.py", line 647, in run
  File "master:/home/dygland/git/ansible/.venv/ansible14/lib64/python3.12/site-packages/ansible/modules/dnf.py", line 539, in list_items
  File "master:/home/dygland/git/ansible/.venv/ansible14/lib64/python3.12/site-packages/ansible/modules/dnf.py", line 484, in _execute_dnf_script
  File "master:/home/dygland/git/ansible/.venv/ansible14/lib64/python3.12/site-packages/mitogen/parent.py", line 2029, in call
    return self.default_call_chain.call(fn, *args, **kwargs)
  File "master:/home/dygland/git/ansible/.venv/ansible14/lib64/python3.12/site-packages/mitogen/parent.py", line 1986, in call
    return receiver.get().unpickle(throw_dead=False)
  File "<stdin>", line 1014, in unpickle
  File "<stdin>", line 1055, in unpickle_iter
mitogen.core.CallError: builtins.TypeError: list_items() missing 1 required positional argument: 'command'
  File "<stdin>", line 4009, in _dispatch_one

```


### Mitogen version

0.3.53

### Ansible version (if applicable)

2.21.3

### OS and environment

Controller: RedHat 10, python 3.12
Target: Redhat 9 or 10, python 3.9 or 3.12

### Steps to reproduce

Steps:
run the following task in a playbook

```yaml
- name: find all available packages
   ansible.builtin.dnf
     list: "httpd-*"
    register: available_packages
```


### Anything else

This works fine on mitogen 0.3.53 on ansible 2.16 targeting RedHat 8 or 9 hosts. so there is some changes that have been made by ansible and not in mitogen.

**Comment by moreati** [comment]
Replicated
```
➜  mitogen git:(master) ✗ ANSIBLE_STRATEGY_PLUGINS=~/src/mitogen/ansible_mitogen/plugins/strategy ANSIBLE_STRATEGY=mitogen_linear .venv/bin/ansible -m ansible.builtin.dnf -a"list=httpd-*" a10.lan
[WARNING]: Deprecation warnings can be disabled by setting `deprecation_warnings=False` in ansible.cfg.
[DEPRECATION WARNING]: Use of strategy plugins not included in ansible.builtin are deprecated and do not carry any backwards compatibility guarantees. No alternative for third party strategy plugins is currently planned. This feature will be removed from ansible-core in a future release.
[WARNING]: Host 'a10.lan' is using the discovered Python interpreter at '/usr/bin/python3.12', but future installation of another Python interpreter could cause a different interpreter to be discovered. See https://docs.ansible.com/ansible-core/2.21/reference_appendices/interpreter_discovery.html for more information.
[ERROR]: Task failed: Action failed: Module result deserialization failed: No start of json char found

Task failed: Action failed.
Origin: <adhoc 'ansible.builtin.dnf' task>

{'action': 'ansible.builtin.dnf', 'args': {'list': 'httpd-*'}, 'timeout': 0, 'async_val': 0, 'poll': 15}

<<< caused by >>>

Module result deserialization failed: No start of json char found See stdout/stderr for the returned output.

a10.lan | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.12"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"master:/Users/alex/src/mitogen/ansible_mitogen/runner.py\", line 1062, in _run\n    self._run_code(code, mod)\n  File \"master:/Users/alex/src/mitogen/ansible_mitogen/runner.py\", line 1017, in _run_code\n    exec(code, vars(mod))\n  File \"master:/Users/alex/src/mitogen/.venv/lib/python3.14/site-packages/ansible/modules/dnf.py\", line 675, in <module>\n  File \"master:/Users/alex/src/mitogen/.venv/lib/python3.14/site-packages/ansible/modules/dnf.py\", line 671, in main\n  File \"master:/Users/alex/src/mitogen/.venv/lib/python3.14/site-packages/ansible/modules/dnf.py\", line 647, in run\n  File \"master:/Users/alex/src/mitogen/.venv/lib/python3.14/site-packages/ansible/modules/dnf.py\", line 539, in list_items\n  File \"master:/Users/alex/src/mitogen/.venv/lib/python3.14/site-packages/ansible/modules/dnf.py\", line 484, in _execute_dnf_script\n  File \"master:/Users/alex/src/mitogen/mitogen/parent.py\", line 2029, in call\n    return self.default_call_chain.call(fn, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"master:/Users/alex/src/mitogen/mitogen/parent.py\", line 1986, in call\n    return receiver.get().unpickle(throw_dead=False)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<stdin>\", line 1014, in unpickle\n  File \"<stdin>\", line 1055, in unpickle_iter\nmitogen.core.CallError: builtins.TypeError: list_items() missing 1 required positional argument: 'command'\n  File \"<stdin>\", line 4009, in _dispatch_one\n\n",
    "module_stdout": "",
    "msg": "Module result deserialization failed: No start of json char found",
    "rc": 1
}
```
```
➜  mitogen git:(master) ✗ .venv/bin/ansible --version                      
ansible [core 2.21.4]
  config file = /Users/alex/.ansible.cfg
  configured module search path = ['/Users/alex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alex/src/mitogen/.venv/lib/python3.14/site-packages/ansible
  ansible collection location = /Users/alex/.ansible/collections:/usr/share/ansible/collections
  executable location = .venv/bin/ansible
  python version = 3.14.7 (main, Sep  1 2026, 14:05:28) [Clang 22.1.3 ] (/Users/alex/src/mitogen/.venv/bin/python3)
  jinja version = 3.1.6
  pyyaml version = 6.0.3 (with libyaml v0.2.5)
```

**Comment by moreati** [comment]
Please try rev https://github.com/mitogen-hq/mitogen/commit/39374260500bf9db7d8692b65723e4d730b2a082 from PR #1560
